require("config.autocommands")
require("config.colors")
require("config.keymaps")
require("config.options")
require("config.plugins")

-- plugins
require("plugins.oil")
require("plugins.cmp")
require("plugins.mini")
require("plugins.fidget")
require("plugins.wilder")
require("plugins.lspzero")
require("plugins.autosave")
require("plugins.lspconfig")
require("plugins.toggleterm")
require("plugins.ts-autotag")
require("plugins.treesitter")
