local lspconfig = require("lspconfig")

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snipperSupport = true

lspconfig.bashls.setup({})
lspconfig.jqls.setup({})
lspconfig.jsonls.setup({})
lspconfig.lua_ls.setup({})
lspconfig.markdown_oxide.setup({})
lspconfig.nil_ls.setup({})
lspconfig.cssls.setup({})
lspconfig.ccls.setup({ capabilities = capabilities })
lspconfig.sqls.setup({})
lspconfig.gopls.setup({})
lspconfig.nextls.setup({})
lspconfig.htmx.setup({})
lspconfig.html.setup({})
lspconfig.eslint.setup({})
lspconfig.marksman.setup({})
lspconfig.ruff.setup({})
lspconfig.pylsp.setup({})
lspconfig.vimls.setup({})
lspconfig.jdtls.setup({})
lspconfig.yamlls.setup({})
lspconfig.bashls.setup({})
lspconfig.svelte.setup({})
lspconfig.autotools_ls.setup({})
lspconfig.ts_ls.setup({})
lspconfig.tailwindcss.setup({})
lspconfig.rust_analyzer.setup({})
